"""encrypted_totp_secret

Revision ID: 57a060b53c8f
Revises: 755d0a5104ac
Create Date: 2026-04-30 09:20:38.692572

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '57a060b53c8f'
down_revision = '755d0a5104ac'
branch_labels = None
depends_on = None


def upgrade():
    # Widen the column to fit Fernet ciphertext (~100 chars + version prefix).
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column(
            'totp_secret',
            existing_type=sa.VARCHAR(length=64),
            type_=sa.String(length=255),
            existing_nullable=True,
        )

    # Clear any pre-existing plaintext TOTP secrets — every legitimate
    # secret from this migration onward is `v1:<fernet>`, never raw
    # base32. A legacy plaintext row would silently fail decryption at
    # verification time, which is worse than forcing the user back
    # through enrolment. Operators should re-enrol any TOTP-required
    # users (compliance, admin) immediately after this migration runs.
    op.execute(
        "UPDATE users SET totp_secret = NULL, totp_enrolled_at = NULL "
        "WHERE totp_secret IS NOT NULL AND totp_secret NOT LIKE 'v1:%'"
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('totp_secret',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###
