"""training

Revision ID: 755d0a5104ac
Revises: 6a3fd71b5fe8
Create Date: 2026-04-30 08:09:55.528286

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '755d0a5104ac'
down_revision = '6a3fd71b5fe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_courses',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('training_assignments',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('role_code', sa.String(length=32), nullable=True),
    sa.Column('line_id', sa.String(length=36), nullable=True),
    sa.Column('recurrence_months', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['training_courses.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_course_versions',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('title', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('pass_threshold', sa.Float(), nullable=False),
    sa.Column('validity_months', sa.Integer(), nullable=False),
    sa.Column('link_ttl_days', sa.Integer(), nullable=False),
    sa.Column('exam_time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['training_courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'version', name='uq_course_version')
    )
    op.create_table('trainees',
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role_code', sa.String(length=32), nullable=False),
    sa.Column('line_id', sa.String(length=36), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trainees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trainees_phone'), ['phone'], unique=True)

    op.create_table('training_modules',
    sa.Column('course_version_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.JSON(), nullable=False),
    sa.Column('body_md', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_version_id'], ['training_course_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_version_id', 'order_index', name='uq_module_version_order')
    )
    op.create_table('training_questions',
    sa.Column('course_version_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.JSON(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_version_id'], ['training_course_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_version_id', 'order_index', name='uq_question_version_order')
    )
    op.create_table('training_answer_options',
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.JSON(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['training_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_enrolments',
    sa.Column('trainee_id', sa.String(length=36), nullable=False),
    sa.Column('course_version_id', sa.String(length=36), nullable=False),
    sa.Column('magic_token', sa.String(length=255), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_ref', sa.String(length=64), nullable=True),
    sa.Column('module_progress', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_version_id'], ['training_course_versions.id'], ),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_enrolments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_enrolments_magic_token'), ['magic_token'], unique=True)

    op.create_table('training_attempts',
    sa.Column('enrolment_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enrolment_id'], ['training_enrolments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrolment_id')
    )
    op.create_table('training_declarations',
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('typed_name', sa.String(length=120), nullable=False),
    sa.Column('signature_png', sa.LargeBinary(), nullable=True),
    sa.Column('declaration_text', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['training_attempts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id')
    )
    op.create_table('training_certifications',
    sa.Column('trainee_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('course_version_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('declaration_id', sa.String(length=36), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['training_attempts.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['training_courses.id'], ),
    sa.ForeignKeyConstraint(['course_version_id'], ['training_course_versions.id'], ),
    sa.ForeignKeyConstraint(['declaration_id'], ['training_declarations.id'], ),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_certifications')
    op.drop_table('training_declarations')
    op.drop_table('training_attempts')
    with op.batch_alter_table('training_enrolments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_enrolments_magic_token'))

    op.drop_table('training_enrolments')
    op.drop_table('training_answer_options')
    op.drop_table('training_questions')
    op.drop_table('training_modules')
    with op.batch_alter_table('trainees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trainees_phone'))

    op.drop_table('trainees')
    op.drop_table('training_course_versions')
    op.drop_table('training_assignments')
    op.drop_table('training_courses')
    # ### end Alembic commands ###
